ログインページとサインアップページを追加
Hackathon-2024spring/yomitai pull request #4
Opened 2024-04-29 08:43 UTC by Takahito-Uchino

ログインページとサインアップページを作りました。
スタイルはまだ当たっていません。

2024-04-29 13:46 UTC, kunipico requested changes
修正をお願いします。

2024-04-29 13:46 UTC, kunipico commented on frontend/app/src/pages/signup.tsx
> +          <input id="password" className="border" {...register("password", { required: true })} type="password" placeholder="Password" />
パスワード入力フォームについて、idが同一である旨のワーニングが発生していますので、異なるidになるように修正をお願いします。

2024-04-29 13:53 UTC, Takahito-Uchino commented on frontend/app/src/pages/signup.tsx
> +          <input id="password" className="border" {...register("password", { required: true })} type="password" placeholder="Password" />
修正しました！

2024-04-29 14:04 UTC, kunipico submitted a review, later dismissed
確認しました。

2024-04-29 14:29 UTC, kunipico requested changes

2024-04-29 14:29 UTC, kunipico commented on frontend/app/src/pages/signup.tsx
> +  password: string
SignupForm型の定義の中にパスワード確認用の型が定義されていないようです。
無くても問題なかったでしょうか？

12行目のdataオブジェクトに入力値を反映させてコンソールに表示していますが、
27行目と31行目の...register("password・・・の部分が同じになっているので、
異なるパスワードが入力された際、”パスワード入力”のデータが”パスワード入力確認用”のデータに置き換わってしまいます。

修正お願いします。

2024-04-30 11:19 UTC, kunipico approved these changes
修正内容確認しました。
承認します！

2024-04-30 11:20 UTC, merged